services:
  mongo:
    image: mongo:7
    container_name: taskflow-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taskflow-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
      - PORT=4000
      - CLIENT_ORIGIN=http://localhost:5173
      - JWT_SECRET=change_me_in_prod
      - MONGO_URI=mongodb://mongo:27017/taskflow
    depends_on:
      - mongo

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: taskflow-frontend
    restart: unless-stopped
    ports:
      - "5173:5173"
    environment:
      - VITE_API_BASE_URL=http://localhost:4000
    depends_on:
      - backend

volumes:
  mongo-data:



